apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
    runon: fargate
spec:
  selector:
    matchLabels:
      app: coit-frontend
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        runon: fargate
        app: coit-frontend                                  # 6
        app.kubernetes.io/name: myapp-frontend
    spec:
      containers:
        - image: basilvarghese/myapp-frontend:latest
          imagePullPolicy: Always                         # 7
          name: coit-frontend
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_NAME
              value: mydb
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 100m
              memory: 150Mi
