apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../resources

namespace: dev

replicas:
- name: coit-frontend
  count: 2

namePrefix: customer1-
nameSuffix: -dev

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: coit-frontend
      spec:
        template:
          spec:
            containers:
              - name: coit-frontend
                image: basilvarghese/coit-frontend:1.0.0      
    target:
      labelSelector: "app=coit-frontend"
